services:
  postgres:
    image: postgres:17
    restart: unless-stopped
    ports: 
    - 5432:5432
    environment:
    - POSTGRES_USER=ADMIN
    - POSTGRES_PASSWORD=ADMIN
    - POSTGRES_DB=llop_ap
    volumes:
      - pgdata:/var/lib/postgresql/data
  valkey:
    image: valkey/valkey:8-alpine
    restart: unless-stopped
    ports:
      - 6379:6379

volumes:
  pgdata:
